<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:amh="urn:boldensele:xslt"
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
    xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
    xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
    xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
    xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:xml="http://www.w3.org/XML/1998/namespace"
    xmlns="http://www.tei-c.org/ns/1.0"
    exclude-result-prefixes="office text style table fo svg xlink dc meta xml">

  <xsl:output method="xml" encoding="UTF-8" indent="yes" omit-xml-declaration="no"/>

  <!-- Témoins reconnus dans l'apparat -->
<xsl:variable name="temoins" as="xs:string*"
    select="('Li', 'U', 'Wo', 'Deluz')"/>

<xsl:function name="amh:wit" as="xs:string?">
    <xsl:param name="lecture" as="xs:string"/>

    <xsl:variable name="tokens"
        select="tokenize(normalize-space(translate($lecture, '&#xA0;',' ')), '\s+')"/>

    <xsl:variable name="witnesses"
        select="distinct-values($tokens[. = $temoins])"/>

    <xsl:sequence
        select="string-join($witnesses ! concat('#', .), ' ')"/>
</xsl:function>

<xsl:function name="amh:lecture" as="xs:string">
    <xsl:param name="lecture" as="xs:string"/>

    <xsl:variable name="tokens"
        select="tokenize(normalize-space(translate($lecture, '&#xA0;',' ')), '\s+')"/>

    <xsl:sequence
        select="string-join($tokens[not(. = $temoins)], ' ')"/>
</xsl:function>

  <xsl:function name="amh:style-parent" as="xs:string?">
        <xsl:param name="element" as="element()"/>

        <xsl:variable name="style-name"
            select="$element/@text:style-name"/>

        <xsl:sequence
            select="root($element)//style:style[
                @style:name = $style-name
            ]/@style:parent-style-name"/>
    </xsl:function>

  <!-- Racine -->
  <xsl:template match="/">
    <TEI>
      <teiHeader>
        <fileDesc>
          <titleStmt>
            <title>
              <xsl:value-of select="normalize-space(/office:document/office:meta/dc:title)"/>
            </title>
          </titleStmt>
          <publicationStmt>
            <p>Source ODT converted to TEI.</p>
          </publicationStmt>
          <sourceDesc>
            <p>ODT document generated by LibreOffice.</p>
          </sourceDesc>
        </fileDesc>
      </teiHeader>
      <text>
        <body>
          <xsl:apply-templates select="/office:document/office:body/office:text"/>
        </body>
      </text>
    </TEI>
  </xsl:template>

  <xsl:template match="office:text">
    <xsl:apply-templates select="*"/>
  </xsl:template>

  <xsl:template match="text:section[@text:name = 'prologue']">
    <div type="prologue">
        <xsl:apply-templates/>
    </div>
  </xsl:template>

    <xsl:template match="text:section[starts-with(@text:name, 'chapitre-')]">
    <div type="chapter" n="{substring-after(@text:name, 'chapitre-')}">
        <xsl:apply-templates/>
    </div>
  </xsl:template>

  <xsl:template match="*[self::text:p or self::text:h][
    (@text:style-name = 'amh_5f_paragraphe'
    or @text:style-name = 'amh_5f_premier_5f_paragraphe'
    or amh:style-parent(.) = 'amh_5f_paragraphe'
    or amh:style-parent(.) = 'amh_5f_premier_5f_paragraphe')
    and not(@text:style-name = 'amh_5f_vers' or amh:style-parent(.) = 'amh_5f_vers')
]">
    <p>
        <xsl:apply-templates/>
    </p>
</xsl:template>

  <xsl:template match="text:section[starts-with(@text:name, 'vers-grp-')]">
    <lg>
        <xsl:apply-templates/>
    </lg>
</xsl:template>

  <xsl:template match="*[self::text:p or self::text:h][
        amh:style-parent(.) = 'amh_5f_titre_5f_chapitre'
    ]">
        <head>
            <xsl:apply-templates/>
        </head>
    </xsl:template>

    <xsl:template match="*[self::text:p or self::text:h][@text:style-name = 'amh_5f_vers' or amh:style-parent(.) = 'amh_5f_vers']">
    <l>
        <xsl:apply-templates/>
    </l>
</xsl:template>

    <xsl:template match="text:span[@text:style-name = 'amh_5f_lettre_5f_rubriquee']">
    <hi rend="rubricated">
        <xsl:apply-templates/>
    </hi>
</xsl:template>

  <xsl:template match="text:span[@text:style-name = 'amh_5f_foliotation']">
    <pb n="{replace(
        normalize-space(.),
        '^\[f\.[ &#xA0;]*([0-9]+[rv])\]$',
        '$1'
    )}"/>
</xsl:template>

<xsl:template match="text:note[
    descendant::text:span[
        @text:style-name = 'amh_5f_apparat_5f_commentaire'
    ]
    and not(
        descendant::text:span[
            @text:style-name = (
                'amh_5f_apparat_5f_témoin',
                'amh_5f_apparat_5f_variante',
                'amh_5f_apparat_5f_omission',
                'amh_5f_apparat_5f_correction',
                'amh_5f_apparat_5f_addition',
                'amh_5f_apparat_5f_paleo'
            )
        ]
    )
]">
    <xsl:variable name="source"
    select="string-join(
        text:note-body/text:p/text:span[
            @text:style-name = 'amh_5f_apparat_5f_commentaire'
        ],
        ''
    )"/>

    <note type="source">
        <xsl:value-of select="replace(
            normalize-space($source),
            '^\((.*)\)$',
            '$1')
        "/>
    </note>
</xsl:template>

<xsl:template match="text:note[
    descendant::text:p[
        @text:style-name = 'amh_5f_note_5f_apparat'
        or amh:style-parent(.) = 'amh_5f_note_5f_apparat'
    ]
    and contains(string(text:note-body), ':')
]">

    <xsl:variable name="apparat"
        select="normalize-space(string(text:note-body))"/>

    <xsl:variable name="lemme"
        select="normalize-space(substring-before($apparat, ':'))"/>

    <xsl:variable name="variantes"
        select="normalize-space(substring-after($apparat, ':'))"/>

    <app>

        <lem>
            <xsl:choose>

                <xsl:when test="contains($lemme, 'corr. ed.')">

                    <xsl:attribute name="resp">#AMH</xsl:attribute>

                    <xsl:value-of
                        select="
                            normalize-space(
                                translate(
                                    replace(
                                        $lemme,
                                        '\s*corr\.\s*ed\.\s*',
                                        ''
                                    ),
                                    '&#xA0;',
                                    ' '
                                )
                            )
                        "/>

                </xsl:when>

                <xsl:otherwise>

                    <xsl:if test="amh:wit($lemme)">
                        <xsl:attribute name="wit"
                            select="amh:wit($lemme)"/>
                    </xsl:if>

                    <xsl:value-of
                        select="
                            normalize-space(
                                replace(
                                    amh:lecture($lemme),
                                    '\s*\([^)]*script\.[^)]*\)\s*',
                                    ' '
                                )
                            )
                        "/>

                </xsl:otherwise>

            </xsl:choose>
        </lem>

        <xsl:for-each select="tokenize($variantes, '\s*\|\s*')">

            <xsl:variable name="variante"
                select="
                    normalize-space(
                        translate(., '&#xA0;', ' ')
                    )
                "/>

            <xsl:variable name="omission"
                select="matches($variante, '(^|\s)om\.($|\s)')"/>

            <xsl:variable name="addition"
                select="matches($variante, '(^|\s)add\.($|\s)')"/>

            <xsl:variable name="corrompue"
                select="contains($variante, '(lectio corrupta)')"/>

            <xsl:variable name="douteuse"
                select="contains($variante, '(lectio dubia)')"/>

            <rdg>

                <xsl:if test="amh:wit($variante)">
                    <xsl:attribute name="wit"
                        select="amh:wit($variante)"/>
                </xsl:if>

                <xsl:if test="$addition">
                    <xsl:attribute name="type">addition</xsl:attribute>
                </xsl:if>

                <xsl:if test="$corrompue">
                    <xsl:attribute name="type">corrupt</xsl:attribute>
                </xsl:if>

                <xsl:if test="$douteuse">
                    <xsl:attribute name="cert">low</xsl:attribute>
                </xsl:if>

                <xsl:if test="not($omission)">

                    <xsl:value-of
                        select="
                            normalize-space(
                                replace(
                                    replace(
                                        replace(
                                            replace(
                                                amh:lecture($variante),
                                                '\s*\([^)]*script\.[^)]*\)\s*',
                                                ' '
                                            ),
                                            '\s*\(lectio corrupta\)\s*',
                                            ' '
                                        ),
                                        '\s*\(lectio dubia\)\s*',
                                        ' '
                                    ),
                                    '(^|\s)add\.($|\s)',
                                    ' '
                                )
                            )
                        "/>

                </xsl:if>

            </rdg>

        </xsl:for-each>

    </app>

</xsl:template>

<xsl:template match="text:span[
    @text:style-name = 'amh_5f_dev_5f_abbr'
     and not(descendant::text:note)]">
    <ex>
        <xsl:apply-templates/>
    </ex>
</xsl:template>

<xsl:template match="text:span[
    @text:style-name = 'amh_5f_dev_5f_abbr'
    and descendant::text:note
]">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match="text:span[
    @text:style-name = 'amh_5f_nombre_5f_romain'
]">
    <num type="cardinal">
        <xsl:value-of select="upper-case(.)"/>
    </num>
</xsl:template>

<!-- Suppression des commentaires de relecture -->
<xsl:template match="office:annotation | office:annotation-end | text:note-citation"/>

<xsl:template match="
    text:span[
        @text:style-name = 'amh_5f_ancre_5f_glossaire'
        or @text:style-name = 'amh_5f_ancre_5f_index_5f_locorum'
        or @text:style-name = 'amh_5f_ancre_5f_index_5f_nominum'
        or @text:style-name = 'amh_5f_ancre_5f_index_5f_fontium'
    ]
"/>

</xsl:stylesheet>
