name: Validation RNG

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
        - name : Récupérer le dépôt
          uses: actions/checkout@v5

        - name: Installer Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin'
            java-version: '17'
        
        - name: Télécharger Jing
          run: |
            curl -L -o jing.zip https://github.com/relaxng/jing-trang/releases/download/V20220510/jing-20220510.zip
            unzip jing.zip
        
        - name: Vérifier jing
          run: |
            ls
            ls jing-20220510
            ls jing-20220510/bin

        - name: Vérifier l’arborescence
          run: |
            ls -R
          
        - name: Valider les fichiers XML de test
          run: |
            shopt -s nullglob
            files=(tei/glossaire/test/*.xml)

            if [ ${#files[@]} -eq 0 ]; then
            echo "Aucun fichier XML trouvé dans tei/glossaire/test/"
            exit 1
            fi

            FAIL=0

            for file in "${files[@]}"; do
              echo "================================"
              echo "Validation de $file"
              if java -jar jing-20220510/bin/jing.jar schemas/glossaire-tei.rng "$file"; then
                echo "Validation réussie pour $file"
              else
                echo "Validation échouée pour $file"
                FAIL=1
              fi
            done

            echo "================================"
            if [ $FAIL -ne 0 ]; then
              echo "Validation échouée pour au moins un fichier."
              exit 1
            else
              echo "Tous les fichiers ont été validés avec succès."
            fi

        - name: Notification Discord succès
          if: success()
          run: |
            curl -H "Content-Type: application/json" \
              -d '{"content":"✅ Validation RNG : success — halex02/boldensele-numerique — branche main"}' \
              "${{ secrets.DISCORD_WEBHOOK_URL }}" 
        - name: Notification Discord échec
          if: failure()
          run: |
            curl -H "Content-Type: application/json" \
              -d '{"content":"❌ Validation RNG : failure — halex02/boldensele-numerique — branche main"}' \
              "${{ secrets.DISCORD_WEBHOOK_URL }}"
